force-app/main/default/objects/Approval_Step__c/Approval_Step__c.object-meta.xml
<CustomObject>
    <label>Approval Step</label>
    <nameField>
        <label>Approval Steps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Step__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Approval Steps</relationshipLabel>
    <relationshipName>Approval_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Step__c/fields/Step_No__c.field-meta.xml
<CustomField>
    <fullName>Step_No__c</fullName>
    <label>Step No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProgressBarController.cls
public with sharing class ProgressBarController {
    public ProgressBarController() {

    }

    @AuraEnabled
    public static list<Approval_Step__c> getProgressStatus(String accountId){
        list<Approval_Step__c> stepsList = null;
        try {
            stepsList = [select id, name,step_no__c, account__c from Approval_Step__c where account__c =:accountId order by step_no__c ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return stepsList;
    }
}